eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER
      
spring:      
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/EmployeeRealm
  


